extends: [[spectral:oas, all]]

rules:
  # Customize severity of built-in rules
  openapi-tags: error
  operation-tags: error
  operation-operationId: error
  operation-description: error
  
  # Operation responses
  operation-success-response:
    description: Operation must have at least one 2xx or 3xx response
    given: $.paths.*.*.responses
    severity: error
    then:
      function: schema
      functionOptions:
        schema:
          type: object
          minProperties: 1
          propertyNames:
            pattern: "^[2-3][0-9][0-9]$"

  # Check info object completeness  
  info-contact:
    description: Info object should contain a contact object
    given: $.info
    severity: warn
    then:
      field: contact
      function: truthy
      
  info-description:
    description: Info object should contain a description
    given: $.info
    severity: error
    then:
      field: description
      function: truthy 