openapi: 3.0.3
info:
  title: Ringer Mobile Product API
  description: |
    Comprehensive description of the Ringer Mobile API product.
    
    ## Authentication
    This API uses token-based authentication. You need to include an API token in the Authorization header of your requests.
        
    Example: `Authorization: Bearer YOUR_API_TOKEN`
        
    Contact your account manager to obtain a token.
    
    ## Overview
    [Include detailed information about what this API does and how it can be used]
  version: 1.0.0
  license:
    name: MIT License
    url: https://github.com/teliax/ringer-oapi/blob/main/LICENSE
  contact:
    name: Ringer API Support
    url: https://docs.ringer.tel/support
    email: support@ringer.tel

# Multiple server environments
servers:
  - url: https://api.ringer.tel/v1
    description: Production server
  - url: https://api.staging.ringer.tel/v1
    description: Staging server

# Global security definition for token-based authentication
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Bearer Token Authentication
        
        Authenticate by including an API token in the Authorization header of your requests.
        
        Example: `Authorization: Bearer YOUR_API_TOKEN`
        
        Contact your account manager to obtain a token.

# Apply bearer token security globally
security:
  - bearerAuth: 

# Tags for organizing endpoints in the documentation
tags:
  - name: Users
    description: User management endpoints
  - name: Devices
    description: Device management endpoints
  - name: Notifications
    description: Push notification endpoints
  - name: Analytics
    description: Mobile analytics endpoints

paths:
  # Example endpoint with path parameter
  /user/{userId}:
    get:
      tags:
        - Users
      summary: Retrieve user by ID
      description: |
        Retrieves detailed information about a specific user.
      operationId: getUser
      parameters:
        - name: userId
          in: path
          description: Unique identifier for the user
          required: true
          schema:
            type: string
            example: "usr_12345"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
              example:
                id: "usr_12345"
                email: "user@example.com"
                name: "John Doe"
                status: "active"
                created_at: "2023-01-01T12:00:00Z"
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - insufficient permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  # Endpoint for device registration
  /device/register:
    post:
      tags:
        - Devices
      summary: Register a device
      description: Register a mobile device for push notifications
      operationId: registerDevice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceRegistration'
            example:
              user_id: "usr_12345"
              device_token: "fcm-token-xyz123"
              platform: "android"
              app_version: "1.2.3"
              device_model: "Pixel 6"
      responses:
        '201':
          description: Device registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceResponse'
              example:
                id: "dev_67890"
                user_id: "usr_12345"
                platform: "android"
                status: "active"
                created_at: "2023-01-01T12:00:00Z"
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  # Endpoint for sending notifications
  /notifications/send:
    post:
      tags:
        - Notifications
      summary: Send push notification
      description: Send a push notification to a user or group of users
      operationId: sendNotification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationRequest'
            example:
              users: ["usr_12345"]
              title: "New message"
              body: "You have a new message"
              data:
                message_id: "msg_56789"
                type: "chat"
              priority: "high"
      responses:
        '200':
          description: Notification sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationResponse'
              example:
                notification_id: "notif_98765"
                recipients: 1
                status: "sent"
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  # Endpoint for analytics
  /analytics/events:
    post:
      tags:
        - Analytics
      summary: Track mobile events
      description: Track analytics events from mobile applications
      operationId: trackEvents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventsRequest'
            example:
              device_id: "dev_67890"
              user_id: "usr_12345"
              events:
                - name: "app_open"
                  timestamp: "2023-01-01T12:00:00Z"
                  properties:
                    source: "notification"
                    campaign_id: "camp_12345"
                - name: "button_click"
                  timestamp: "2023-01-01T12:01:30Z"
                  properties:
                    button_id: "signup_btn"
                    screen: "welcome"
      responses:
        '200':
          description: Events tracked successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  events_received:
                    type: integer
                    example: 2
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized - invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  # Reusable schemas
  schemas:
    UserResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique user identifier
          example: "usr_12345"
        email:
          type: string
          description: User email
          format: email
          example: "user@example.com"
        name:
          type: string
          description: User name
          example: "John Doe"
        status:
          type: string
          description: User status
          enum: [active, inactive, pending]
          example: "active"
        created_at:
          type: string
          format: date-time
          description: User creation timestamp
          example: "2023-01-01T12:00:00Z"
      required:
        - id
        - email
        - status
        - created_at

    DeviceRegistration:
      type: object
      properties:
        user_id:
          type: string
          description: User associated with this device
          example: "usr_12345"
        device_token:
          type: string
          description: FCM or APNS device token
          example: "fcm-token-xyz123"
        platform:
          type: string
          description: Mobile platform
          enum: [ios, android]
          example: "android"
        app_version:
          type: string
          description: Application version
          example: "1.2.3"
        device_model:
          type: string
          description: Device model information
          example: "Pixel 6"
      required:
        - user_id
        - device_token
        - platform

    DeviceResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique device identifier
          example: "dev_67890"
        user_id:
          type: string
          description: User associated with this device
          example: "usr_12345"
        platform:
          type: string
          description: Mobile platform
          enum: [ios, android]
          example: "android"
        status:
          type: string
          description: Device status
          enum: [active, inactive]
          example: "active"
        created_at:
          type: string
          format: date-time
          description: Registration timestamp
          example: "2023-01-01T12:00:00Z"
      required:
        - id
        - user_id
        - platform
        - status
        - created_at

    NotificationRequest:
      type: object
      properties:
        users:
          type: array
          description: List of user IDs to notify
          items:
            type: string
          example: ["usr_12345"]
        title:
          type: string
          description: Notification title
          example: "New message"
        body:
          type: string
          description: Notification body
          example: "You have a new message"
        data:
          type: object
          description: Additional data payload
          example:
            message_id: "msg_56789"
            type: "chat"
        priority:
          type: string
          description: Notification priority
          enum: [normal, high]
          example: "high"
      required:
        - users
        - title
        - body

    NotificationResponse:
      type: object
      properties:
        notification_id:
          type: string
          description: Unique notification identifier
          example: "notif_98765"
        recipients:
          type: integer
          description: Number of recipients
          example: 1
        status:
          type: string
          description: Notification status
          enum: [sent, failed, partial]
          example: "sent"
      required:
        - notification_id
        - recipients
        - status

    EventsRequest:
      type: object
      properties:
        device_id:
          type: string
          description: Device identifier
          example: "dev_67890"
        user_id:
          type: string
          description: User identifier
          example: "usr_12345"
        events:
          type: array
          description: List of analytics events
          items:
            type: object
            properties:
              name:
                type: string
                description: Event name
                example: "app_open"
              timestamp:
                type: string
                format: date-time
                description: Event timestamp
                example: "2023-01-01T12:00:00Z"
              properties:
                type: object
                description: Event properties
                example:
                  source: "notification"
                  campaign_id: "camp_12345"
      required:
        - device_id
        - events

    Error:
      type: object
      properties:
        status:
          type: string
          description: Error status
          example: "error"
        error:
          type: string
          description: Error message
          example: "Invalid input parameters"
        error_code:
          type: string
          description: Error code for machine processing
          example: "INVALID_INPUT"
      required:
        - status
        - error 