openapi: 3.0.3
info:
  title: NotADipDip LRN Lookup API
  description: |
    High-performance Local Routing Number (LRN) lookup service for telephone numbers.
    Part of the Telique API ecosystem.
  version: 1.0.0
  contact:
    name: Ringer Support
    url: https://docs.ringer.tel
servers:
  - url: http://localhost:56660
    description: Local development server
  - url: https://api.ringer.tel/notadipdip
    description: Production server
paths:
  /{telephone_number}:
    get:
      summary: Lookup LRN for a telephone number
      description: |
        Query the Local Routing Number (LRN) and Service Profile Identifier (SPID) 
        for a given 10-digit US telephone number.
      operationId: lookupLRN
      parameters:
        - name: telephone_number
          in: path
          required: true
          description: 10-digit US telephone number (NPA-NXX-XXXX format, digits only)
          schema:
            type: string
            pattern: '^[2-9]\d{9}$'
            example: "2125551234"
        - name: format
          in: query
          required: false
          description: Response format
          schema:
            type: string
            enum: [json, xml, plain]
            default: plain
      responses:
        '200':
          description: Successful lookup
          content:
            text/plain:
              schema:
                type: string
                example: "2125550000;ABCD"
                description: "Format: {LRN};{SPID} or just {telephone_number} if not found"
            application/json:
              schema:
                $ref: '#/components/schemas/LRNResponse'
              example:
                telephone_number: 2125551234
                lrn: 2125550000
                spid: "ABCD"
                status: "found"
            application/xml:
              schema:
                type: string
                example: |
                  <?xml version="1.0" encoding="UTF-8"?>
                  <lrn_response>
                    <telephone_number>2125551234</telephone_number>
                    <lrn>2125550000</lrn>
                    <spid>ABCD</spid>
                    <status>found</status>
                  </lrn_response>
        '400':
          description: Invalid telephone number format
          content:
            text/plain:
              schema:
                type: string
                example: "BADCOMMAND"
components:
  schemas:
    LRNResponse:
      type: object
      properties:
        telephone_number:
          type: integer
          format: int64
          description: The queried telephone number
          example: 2125551234
        lrn:
          type: integer
          format: int64
          nullable: true
          description: The Local Routing Number (null if not found)
          example: 2125550000
        spid:
          type: string
          nullable: true
          description: The Service Profile Identifier (null if not found)
          pattern: '^[A-Z0-9]{4}$'
          example: "ABCD"
        status:
          type: string
          enum: [found, not_found]
          description: Lookup status
          example: "found"
      required:
        - telephone_number
        - status
 