openapi: 3.0.3
info:
  title: IVY API - Country Codes
  description: Country Codes management endpoints for the IVY API
  version: 1.0.0
paths:
openapi: 3.0.3
info:
  title: IVY API - Country Codes
  description: Country Codes endpoints for the IVY API
  version: 1.0.0
paths:
  /country-codes:
    get:
      tags:
        - Country Codes
      summary: List of Country Codes
      description: A list of country codes.
      operationId: list_country_codes
      parameters:
        - name: Authorization
          in: header
          description: This token is used to authenticate a particular account.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Array of Country Codes
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/CountryCodeList'
        "400":
          description: Bad Request Parameters or Validation Errors
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/error'
        "401":
          description: Unauthorized request. This error will occur if the SecurityContext header is not provided or does not include a party_id.
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/error' 