openapi: 3.0.3
info:
  title: IVY API - Password
  description: Password management endpoints for the IVY API
  version: 1.0.0
paths:
  /password:
    post:
      tags:
        - Forgot Password
      summary: Forgot User Password
      description: Enter your email used to login to your account. The response will email you a password reset link.
      operationId: forgot_password
      requestBody:
        description: Email Address Attribute
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/ForgotPasswordParams'
      responses:
        "201":
          description: Reset Password token
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ForgotPassword'
        "400":
          description: Bad Request Parameters or Validation Errors
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/error'
  
  /password/reset:
    put:
      tags:
        - Forgot Password
      summary: Reset Password with Reset Password Token
      description: Once you get the reset_token reset your password with it.
      operationId: reset_password
      requestBody:
        description: Reset Password Token
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/ResetPasswordParams'
      responses:
        "201":
          description: Password Reset
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/ResetPassword'
        "400":
          description: Bad Request Parameters or Validation Errors
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/error' 