openapi: 3.0.3
info:
  title: IVY API - Sign Up
  description: Sign Up endpoints for the IVY API
  version: 1.0.0
paths:
  /sign-up:
    post:
      tags:
        - Sign Up
      summary: Sign Up
      description: Sign Up as a Customer
      operationId: sign_up
      requestBody:
        description: Customer Registration Parameters
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yaml#/components/schemas/CustomerRegistrationParams'
      responses:
        "201":
          description: Customer Created.
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/CustomerRegistration'
        "400":
          description: Bad Request Parameters or Validation Errors
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/error'
        "401":
          description: Unauthorized request. This error will occur if the SecurityContext header is not provided or does not include a party_id.
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/error'
        "404":
          description: Couldn't find account record
          content:
            application/json:
              schema:
                $ref: './components.yaml#/components/schemas/error' 