name: Trigger Docs Update

on:
  push:
    branches:
      - main
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.json'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository_dispatch
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            https://api.github.com/repos/teliax/ringer-docs/dispatches \
            -d '{"event_type":"ringer-oapi-update"}'
